src/SimpleWebPage/Models/VMR.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SimpleWebPage.Models
{


    public class Meta
    {
        public int limit { get; set; }
        public string next { get; set; }
        public int offset { get; set; }
        public object previous { get; set; }
        public int total_count { get; set; }
    }

    public class Alias
    {
        public string alias { get; set; }
        public string conference { get; set; }
        public string creation_time { get; set; }
        public string description { get; set; }
        public Nullable<int> id { get; set; }
    }

    public class IvrTheme
    {
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public string uuid { get; set; }
    }

    public class VMR : System.IComparable<VMR>
    {
        public List<Alias> aliases { get; set; }
        public bool allow_guests { get; set; }
        public List<object> automatic_participants { get; set; }
        public string call_type { get; set; }
        public string creation_time { get; set; }
        public string description { get; set; }
        public bool enable_overlay_text { get; set; }
        public bool force_presenter_into_main { get; set; }
        public string guest_pin { get; set; }
        public object guest_view { get; set; }
        public string host_view { get; set; }
        public Nullable<int> id { get; set; }
        public IvrTheme ivr_theme { get; set; }
        public string match_string { get; set; }
        public object max_callrate_in { get; set; }
        public object max_callrate_out { get; set; }
        public object mssip_proxy { get; set; }
        public bool mute_all_guests { get; set; }
        public string name { get; set; }
        public object participant_limit { get; set; }
        public string pin { get; set; }
        public string primary_owner_email_address { get; set; }
        public string replace_string { get; set; }
        public string resource_uri { get; set; }
        public string service_type { get; set; }
        public string sync_tag { get; set; }
        public object system_location { get; set; }
        public string tag { get; set; }

        public int CompareTo(VMR that)
        {
            int result = this.id.Value.CompareTo(that.id.Value);

            return result;
            
        }
    }

    public class RootObjectVMR
    {
        public Meta meta { get; set; }
        public List<VMR> objects { get; set; }
    }

    public class RootObjectAlias
    {
        public Meta meta { get; set; }
        public List<Alias> objects { get; set; }
    }
}

src/SimpleWebPage/Controllers/VMRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SimpleWebPage.Obj;
using SimpleWebPage.Models;
using System.Collections;
using SimpleWebPage.Data;

namespace SimpleWebPage.Controllers
{
    public class VMRController : Controller
    {
        VMRGetRequests VMRGet = new VMRGetRequests();
        private VMRRepository _vmrRepository = null;

        public VMRController()
        {
            _vmrRepository = new VMRRepository();
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var VMR = _vmrRepository.GetVMR(id.Value);

            return View(VMR);
        }

        public ActionResult Index()
        {

            var VMRList = _vmrRepository.GetVMRList("DeMO");

            return View(VMRList);
        }

    }
}

src/SimpleWebPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/CustomStyling.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Create VMR demo", "Index", "VMR", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Add menu items here -->
                </ul>
            </div>
        </div>
    </div>

    @if (ViewBag.ShowBackBar != null && ViewBag.ShowBackBar)
            {
        <div class="backbar">
            <div class="container">
                @Html.ActionLink("Return to List", "Index", null, new { @class = "btn btn-info" })
            </div>
        </div>
    }

    <div class="container body-content">
        @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Anywhere VMR tools</p>
            </footer>
        </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

src/SimpleWebPage/Views/VMR/Detail.cshtml
@model SimpleWebPage.Models.VMR

@{
    ViewBag.Title = "Big Brother loves you";
    ViewBag.ShowBackBar = true;
}


<h2>@Model.name</h2>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h5><b>Name:</b> @Model.name</h5>
            @if (Model.aliases.ElementAtOrDefault(0) != null)
            {
                <h5><b>URI:</b> @Model.aliases[0].alias</h5>
            }
            @if (Model.aliases.ElementAtOrDefault(1) != null)
            {
                <h5><b>Meeting ID:</b> @Model.aliases[1].alias</h5>
            } 
            <h5><b>Host PIN:</b> @Model.pin</h5>
            <h5><b>Guest PIN:</b> @Model.guest_pin</h5>

            @if (Model.tag != "")
            {
                <br>
                <h5><b>Tag:</b></h5>
                <h5>@Model.tag</h5>
            }

        </div>
    </div>
</div>

src/SimpleWebPage/Views/VMR/Index.cshtml
@model IList<SimpleWebPage.Models.VMR>

@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    @foreach (var vmr in Model)
    {
        <div class="col-md-12">
            <div class="col-sm-6">
                <h4>@Html.ActionLink(vmr.name, "Detail", new { id = vmr.id})</h4>
            </div>

            <div class="col-sm-6">
                <h4>@vmr.description</h4>
            </div>
        </div>
    }
</div>